### ISSUE TITLE
Connection Error after every pc restart

### ISSUE THREAD

**Issue by PurshuRana** [zim32/mysql.dart#11]
Unhandled Exception: Exception: MySQL error: Got timeout reading communication packets

i get the above error while connecting to mysql localhost database for first time after every pc restart.

When this happens, i will connect to database using mysql workbench and then if i restart the flutter app connection happens properly untill next reboot

**Comment by zim32** [comment]
Ok. So to handle this issue, I need to add debug logging first. Than I can ask you to run your app with debug logging enabled and try to figure out whats happening. Because right now it's impossible to guess what happened.

**Comment by PurshuRana** [comment]
> Ok. So to handle this issue, I need to add debug logging first. Than I can ask you to run your app with debug logging enabled and try to figure out whats happening. Because right now it's impossible to guess what happened.
Thank you for your reply, i got the solution, i changed the MYSQL privacy setting to LEGACY MODE, now its working fine
