### ISSUE TITLE
Prepared statement throwing socket exception

### ISSUE THREAD

**Issue by Ehesp** [zim32/mysql.dart#14]
Running a prepared statement on a normal connection throws an exception:

```dart
final stmt = await _connection!.prepare('SELECT * FROM users WHERE foo = ?');
final result = await stmt.execute(['bar']);
await stmt.deallocate();
```

This throws the exception: 

```
Unhandled exception:
Exception: Skipping socket data, because of connection bad state
State: connectionEstablished
Data: [38, 0, 0, 4, 3, 100, 101, 102, 4, 116, 101, 115, 116, 4, 117, 115, 101, 114, 4, 117, 115, 101, 114, 2, 105, 100, 2, 105, 100, 12, 63, 0, 11, 0, 0, 0, 3, 35, 66, 0, 0, 0]
```

Also, if I try:

```dart
final stmt = await _connection!.prepare("SELECT * FROM users WHERE foo = '?'");
```

I get the error that the number of params does not match the provided list.

**Comment by zim32** [comment]
Hi Esherp. Is it happening every time, or sometimes?

**Comment by zim32** [comment]
I can reproduce this issue. I will check

**Comment by zim32** [comment]
Ok fixed here https://github.com/zim32/mysql.dart/commit/bfb1dd6248b08ff822da5f5097ebbdbf41aff278
Release 0.0.14

Waiting for feedback to close this issue.

**Comment by Ehesp** [comment]
Cheers all working
