### ISSUE TITLE
mysql_utils

### ISSUE THREAD

**Issue by biner88** [zim32/mysql.dart#18]
First of all, cheers for the author👍! @zim32

Before mysql_utils 2.0.0, the mysql1 library was used, but the stability was insufficient and the maintenance enthusiasm was not high. Now I decided to switch to mysql_client, I hope the author can continue to maintain and improve, thank you very much!

[mysql_utils](https://pub.dev/packages/mysql_utils)

mysql_utils 2.0.0之前使用的是mysql1库，然而稳定性不足，维护积极性不高. 现在决定切换到mysql_client,希望作者能继续保持维护，继续完善，非常感谢！

**Comment by zim32** [comment]
Thanks. Hope it works well. Keep in mind this is still not stable version and there will be some breaking changes. I will introduce them in 0.2 version

**Comment by zim32** [comment]
But there will be few
