### ISSUE TITLE
Not able to load 0.0.8

### ISSUE THREAD

**Issue by gumdum** [zim32/mysql.dart#2]
Maybe because it is so new, but 0.0.8 is not loading from pub.dev for me. Will go eat and try again in an hour.

**Comment by zim32** [comment]
Maybe some issue with recent dart publish. Please again and tell is it ok?

**Comment by gumdum** [comment]
it's good, downloaded latest

**Comment by zim32** [comment]
Closing. You are first alfa tester ) Good luck and welcome )

**Comment by gumdum** [comment]
getting this error though when I register a singleton:

flutter: Exception: Can not execute query: connecion closed

my code
```
import 'package:mysql_client/mysql_client.dart';

Future<MySQLConnection> initMysql() async {
  final conn = await MySQLConnection.createConnection(
    host: "api.biblebreeze.com",
    port: 3306,
    userName: "bbuser",
    password: "CAqX3bKK_6Zmq52fKJujc_>!^",
    databaseName: "bb", // optional
  );
  return conn;
}
```
in get
```
  getItInstance.registerSingleton<MySQLConnection>(await initMysql());
```

**Comment by zim32** [comment]
You need to call  **await connect();** to actually connect to database
