### ISSUE TITLE
Throw MySQLException rather than Exception

### ISSUE THREAD

**Issue by bsutton** [zim32/mysql.dart#20]
Just trying to adapt your library into my package simple_mysql_orm.

Firstly thanks for the work.

One issue I note is that you throw a generic Exception class from the libraries.

I'm wondering if you would consider changing this it a more specific class such as MySQLException as this makes it easier to catch and differentiate from other possible exceptions.

**Comment by zim32** [comment]
Hi. I've refactored exceptions. Now all general Exceptions are gone. See https://github.com/zim32/mysql.dart/blob/main/lib/exception.dart what's instead.

**Comment by bsutton** [comment]
Can I suggest that they all extend a single base class MySqlException.

This will allow a user to catch any of them worth a single catch clause it
individual exceptions.

I common error code in the base class would also be useful so you can
really detect errors such as login failed, deadlocks etc.

**Comment by zim32** [comment]
Can you see latest code in git and say is it ok now?

**Comment by bsutton** [comment]
Structure looks good.

Is it possible to extract the SQL error code and make it available in the
exception.

i often check for specific error codes

**Comment by zim32** [comment]
Nice feature. I will do it

**Comment by zim32** [comment]
Server error code is now exposed in MySQLServerException throw errorCode prop
Release 0.0.19
