### ISSUE TITLE
column matching is case-sensitive

### ISSUE THREAD

**Issue by bsutton** [zim32/mysql.dart#22]
Just found a problem with the column matching in that this project does a case sensitive match on mysql column names.

Column names in mysql are case insensitive (where as table names are 'normally' case sensitive - depends on platform and settings). 

This just caused our project to break as we changed the third party tool that generates our mysql database. 
The result is that calls to methods such as ResultSetRow.colByName is now failing.

Can I suggest that we push the column defs to lower case and then any column name argument is also pushed to lowercase before we do the match.

**Comment by zim32** [comment]
Yes, this is a bug. I will fix it

**Comment by bsutton** [comment]
Thanks.

**Comment by zim32** [comment]
Fixed in 0.0.24
