### ISSUE TITLE
SocketException (SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = *2.***.***.**1, port = 47680)

### ISSUE THREAD

**Issue by berkayhh** [zim32/mysql.dart#24]
Hi ,
i would test in my Plesk Server with a Database, but its not connecting to the My Database which i in Plesk hosted. 

Thanks for your Reply ! 
Regards.
Berkay

**Comment by zim32** [comment]
Good day. Can you switch logging branch and provide log details? See readme, troubleshooting.

**Comment by berkayhh** [comment]
https://stackoverflow.com/questions/72676720/flutter-mysql-connection-with-plesk-server-mariadb

**Comment by zim32** [comment]
Issue is fixed?
