### ISSUE TITLE
Multiple statements

### ISSUE THREAD

**Issue by Lelelo1** [zim32/mysql.dart#27]
**Multiple statements**

When I run the following sql:

```
SELECT v.entity_id INTO @id FROM catalog_product_entity_varchar v JOIN catalog_product_entity p ON v.entity_id = p.entity_id WHERE v.attribute_id = '283' AND v.value = '889501092529' LIMIT 1;

SELECT v.value INTO @ean FROM catalog_product_entity_varchar v WHERE v.entity_id = @id AND v.attribute_id = '283' LIMIT 1;

(SELECT g.value INTO @image_front FROM catalog_product_entity_media_gallery g, catalog_product_entity_media_gallery_value gv WHERE g.entity_id IN (SELECT r.parent_id FROM catalog_product_relation r WHERE r.child_id = @id) AND g.value_id = gv.`value_id` AND (gv.position = '1') ORDER BY gv.position ASC) LIMIT 1;

(SELECT g.value INTO @image_back FROM catalog_product_entity_media_gallery g, catalog_product_entity_media_gallery_value gv WHERE g.entity_id IN (SELECT r.parent_id FROM catalog_product_relation r WHERE r.child_id = @id) AND g.value_id = gv.`value_id` AND (gv.position = '2') ORDER BY gv.position ASC) LIMIT 1;

SELECT @id, @ean, @image_front, @image_back 
```

...it failes.
It also happened to me with [mysql1](https://github.com/adamlofts/mysql1_dart/issues/136) driver pub package. As stated the code runs fine in phpMyAdmin (and returns one result set). The error code lead to SO posts about needing to specify delimiter.

When I adding it, it fails:

```
DELIMITER ; SELECT v.entity_id INTO @id FROM catalog_product_entity_varchar v JOIN catalog_product_entity p ON v.entity_id = p.entity_id WHERE v.attribute_id = '283' AND v.value = '889501092529' LIMIT 1 ; DELIMITER
```

While this code works fin everywhere:

```
SELECT v.entity_id INTO @id FROM catalog_product_entity_varchar v JOIN catalog_product_entity p ON v.entity_id = p.entity_id WHERE v.attribute_id = '283' AND v.value = '889501092529' LIMIT 1 ;
```

Is it supported to make more statements than one in the same `conn.execute(sql)` call? Also, any help understanding why it not seem to work in (2) Flutter mysql drivers but works in phpMyAdmin would be appreciated.

**Comment by Lelelo1** [comment]
I found the following: https://dev.mysql.com/doc/internals/en/multi-statement.html

**Comment by zim32** [comment]
As you can see multiple statements is still in the roadmap. Right now I am working on refactoring errors, this is more important and hard to implement with all this async stuff under the hood. So... Not now

**Comment by zim32** [comment]
Multiple statements is something that need to be supported and negotiated between client and server and also there some specific things in parsing protocol packages.

**Comment by Lelelo1** [comment]
Which one is it, *Multiple result*?

**Comment by zim32** [comment]
CLIENT_MULTI_STATEMENTS

**Comment by zim32** [comment]
The question is how to handle multiple result sets on select statements. How to return multiple result sets

**Comment by zim32** [comment]
Right now query method returns single ResultSet

**Comment by zim32** [comment]
Should we add another pair of methods like executeMultiple and prepareMultiple?

**Comment by zim32** [comment]
I think good solution is to leave execute and prepare methods as is. Instead make ResultSet extends Iterator, and contain add property called next to it. So it can ve iterated in for loop or manually

**Comment by Lelelo1** [comment]
The above code I posted return one result in phpMyAdmin. (The first `SELECT`s are stored in variables).

**Comment by zim32** [comment]
Ok I will start to research this issue

**Comment by zim32** [comment]
I've pushed recently support for multiple statements to master branch. Can you switch temporary to master branch in your pubspec file and test it? It should now support multiple statements

**Comment by Lelelo1** [comment]
That's super to hear! I will try it the first thing I do on Monday and report back

**Comment by Lelelo1** [comment]
So I did not get any results this time. There is no exception

**Comment by zim32** [comment]
Just iterate over results in for loop. It extends Iterable. See updated docs

**Comment by Lelelo1** [comment]
Yes you can close
