### ISSUE TITLE
UniCode format

### ISSUE THREAD

**Issue by gumdum** [zim32/mysql.dart#3]
I havn't looked at the code, but I think there is a unicode issue. The first snapshot below is my code before I do a remote mysql call. The second is after I do the call and update the tables. The hindi and urdu language sets are winding characters.
![Screen Shot 2022-02-15 at 2 17 24 PM](https://user-images.githubusercontent.com/71924534/154142345-2ec74074-7e35-423b-803b-814743de6408.png)
![Screen Shot 2022-02-15 at 2 15 41 PM](https://user-images.githubusercontent.com/71924534/154142376-56932b93-1226-4bd1-a17d-052633a403b4.png)

**Comment by zim32** [comment]
Thanks for this issue. I will fix it soon. Seems like a wrong character set, but right now there is no way to set charset.
I will ping as soon as I fix it

**Comment by zim32** [comment]
You can try 0.0.9 version. There is fix for UTF8 charset
If you will see problems with existing rows, it may be because they are broken (wrong encoding). Try to delete and recreate them.

Write here your feedback when you try

**Comment by gumdum** [comment]
That fixed it!! Thank you
