### ISSUE TITLE
Connection timed out (OS Error: Connection timed out, errno = 110), address = 10.0.0.2, port = 38528) or/and Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 39328)

### ISSUE THREAD

**Issue by Emirgms** [zim32/mysql.dart#30]
hi my app did work lasterday morning but evening didnt work i didnt change code 

this code lasterday did work but today or lasterday evening didnt work .
im taking connection timeout error
class MySql {
  Future<MySQLConnection> getConnection() async {
    debugPrint("Connecting to mysql server...");

    // create connection
    final conn = await MySQLConnection.createConnection(
        host: "10.0.0.2",
        port: 3306,
        userName: "root",
        password: "*******",
        secure: false
        // optional
        );
    debugPrint(conn.connected.toString());
    await conn.connect();
    debugPrint('conneccted');
    return conn;
  }
},,

another error .
host: "127.0.0.1"
connection refused error

**Comment by Emirgms** [comment]
Restarted application in 884ms.
I/flutter (10318): Connecting to mysql server...
I/flutter (10318): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (10318): │ #0   MySQLConnection.createConnection
I/flutter (10318): │ #1   MySql.getConnection
I/flutter (10318): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (10318): │ 🐛 Establishing socket connection
I/flutter (10318): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
all log is here

**Comment by zim32** [comment]
If you are in Windows and your app is flutter, try to connect to mysql through console, using mysql client anf then check again.

**Comment by Emirgms** [comment]
i dont know how i can console using mysql client

**Comment by zim32** [comment]
This connection refused comes from OS. There is nothing I can do here

**Comment by Emirgms** [comment]
but this did work lasterday i just push github and its didnt work

**Comment by zim32** [comment]
I don't know your setup. F.e. example I don't know why port number is 39328, not 3306

**Comment by Emirgms** [comment]
i did try another pc but its simple error

**Comment by zim32** [comment]
Where you are connecting from? Where is dart code? And where is mysql server?

**Comment by Emirgms** [comment]
what ? im working localhost. lasterday you did new patch and i have taking error me and other pc

**Comment by MHShetty** [comment]
@Emirgms On which platform are you running your Flutter app on?

**Comment by Emirgms** [comment]
android. my emulator is pixel 3a

**Comment by MHShetty** [comment]
> what ? im working localhost. lasterday you did new patch and i have taking error me and other pc

If your main device/computer is using the usual DHCP instead of static IP assignment, then it's possible that your computer might have got a new IP later after you first configured the proxy/localhost for your computer.

**Comment by zim32** [comment]
> what ? im working localhost. lasterday you did new patch and i have taking error me and other pc

You can revert version, and test. I think the problem is not because of library. That's why I am asking about your setup

**Comment by zim32** [comment]
Because you connection just stops in very early stage, even before library code kicks in

**Comment by MHShetty** [comment]
Please go through one message at a time and then try to figure out what could have possibly gone wrong

**Comment by Emirgms** [comment]
> Also, please go through what @zim32 has suggested once too (connecting to MySQL server, using the default port 3306 instead, etc.), if the above messages don't help.
> 
> Connecting to your MySQL server could be as simple as using your local computer system's terminal to run the `mysql` and then passing the username using the -u option and -p to specify the password (if present).
> 
> If your terminal can't find the `mysql` command then you might need to make sure it's in your PATH.
> 
> How are you interacting with your MySQL server though? If you're using a GUI based application like MySQL workbench, you can try connecting to the database from there and probably run a simple `SELECT 1;` query from there instead.

im using workbench and i connected mysql.i think its no problem , https://stackoverflow.com/a/59217370/10104608) im did everything this website  but i didnt work i will crazy im trying solve this problem 7-8 hours

**Comment by zim32** [comment]
> i foundd !! this problem is mysql options

Can you share what was the cause of the problem?
