### ISSUE TITLE
How to do Resultset to object

### ISSUE THREAD

**Issue by yagizdo** [zim32/mysql.dart#35]
Hi.

Thank you for making such a package. I created a test database myself, there are books in it. When I say Result.assoc, I can see all my books on the console. But no matter what I tried, I could not access those books one by one. I want to list the books I got from my database on the screen. No matter what I tried I couldn't :/ How can I convert to object or at least access only every row :/

![Screen Shot 2022-08-08 at 00 55 16](https://user-images.githubusercontent.com/31064552/183312465-a7de0f5c-5963-4613-b2aa-371f5a5da3c5.png)

<img src="https://user-images.githubusercontent.com/31064552/183312475-383f96b0-53d0-4264-81a4-1ead17a9b679.png" width="500">

**Comment by zim32** [comment]
Hi. You can see example directory in the root of this package.

**Comment by zim32** [comment]
Assos returns you object you need. This is Map so you need somehow map it to your DTO, or you can access columns one by one and convert using this approach

**Comment by zim32** [comment]
This is low level library, so such things as converting data into dto is not covered by this library

**Comment by yagizdo** [comment]
I did it this way. Thank you too for your answer.

![image](https://user-images.githubusercontent.com/31064552/183428529-e7bd4027-9e93-45a8-9e07-b96dcac50e8d.png)
