### ISSUE TITLE
Issue generating a singleton

### ISSUE THREAD

**Issue by gumdum** [zim32/mysql.dart#4]
Maybe it is the state of the connection that is throwing this error. But get_it package will not load the connection properly. I removed the following reference from get_it and it immediately started:

```
  getItInstance.registerSingleton<MySQLConnection>(await initMysql());
```
It looks like you already have a connection established as. a singleton and it is not letting me connect through a global pool. I have to use the example method of connecting only and call conn every time I want to make a call.

Can you remove the singleton?

**Comment by zim32** [comment]
There is no singletones in my code. What error do you have? 
MySQLConnection class is not supposed to be used as a singleton. This is just an ordinary class, each instance of MySQLConnection represents exactly one connection to database

**Comment by zim32** [comment]
Maybe you need to register it as a factory?

**Comment by gumdum** [comment]
I tried factory, factoryasyn, singleton, lazysingleton, singletonasync...the errors were all various but none of the resulted in a global connection.

**Comment by gumdum** [comment]
This is a singleton isn't is
```
 MySQLConnection._({
```

**Comment by gumdum** [comment]
well, maybe someone smarter than me can point it out in the future. For now I 'm jusing using the function initMysql for every place I need to query the database. Thanks for publishing this code. It is very advanced, well thought out and helpful.

**Comment by gumdum** [comment]
You can close this issue. It was registerfactoryasync that was needed

**Comment by zim32** [comment]
I don't know get_it well, but createConnection is async method. Maybe thats why you need  registerfactoryasync.
