### ISSUE TITLE
LAST_INSERT_ID()

### ISSUE THREAD

**Issue by dongri727** [zim32/mysql.dart#46]
Hello, thank you for mysql_client
How can I get the last inserted ID with mysql_client ?

**Comment by sido420** [comment]
Have you tried?

`result.lastInsertID
`

**Comment by zim32** [comment]
Sorry for long answer. Have a hard times now.
Yes you can use https://pub.dev/documentation/mysql_client/latest/mysql_client/IResultSet/lastInsertID.html

**Comment by dongri727** [comment]
thank you both for your help, it works as 

    var lastInsertedId = result.lastInsertID;
    print(lastInsertedId);

if it became BigInt someday, I'll try the second recommend
