### ISSUE TITLE
Unsupported operation: Socket constructor

### ISSUE THREAD

**Issue by gumdum** [zim32/mysql.dart#5]
This is more a feature request to support web. I do not know the requirements, but it'd be an amazing feature to have.

Thank you again for this great package!

**Comment by zim32** [comment]
Socket class is in dart:io package which is not awailable for web platform. How do you suppose it to work from browser? Connect to database directly from web page?

**Comment by gumdum** [comment]
You are correct. There is no javascript mysql client, or way to connect without some type of bridge. The package as is works wonderfully and handles 3/4 of my needs for API management. The remaining 1/4 I'll get through dio http requests. 

Thank you for the quick responses.

**Comment by zim32** [comment]
Theoretically this is possible through proxy:
client  --WS--> proxy --TCP--> mysql

But I've never seen such proxies.
