### ISSUE TITLE
Decode values

### ISSUE THREAD

**Issue by Ehesp** [zim32/mysql.dart#7]
Hello,

Currently all values returned are of type `String`. I understand the type int is provided so it would be possible to convert the values to their Dart type, however is there a built in utility to do this?

**Comment by zim32** [comment]
Hi Esherp. 

There are some design decisions that need to be discussed. 
First of all you are right, Resul Set Rows are converted to Strings.

The second thing to know is that right now you can get column type using 

```
final cols = result.cols.toList();
print(cols[0]!.type);
```
and compare it with constants defined here https://pub.dev/documentation/mysql_client/latest/mysql_protocol/mysql_protocol-library.html (mysqlColumnType...) and write decoder as you whish.

Another design questions are

1) It is inefficient to convert all results both to strings and to some dart data types
2) If such conversion should be made, there should some api to convert it on the fly (maybe you can propose such an api)
3) What to do with such types as Date and DateTime or simple Time. How to deal with Geometry type?

If dart has such feature as Traits in rust, the api could look like

row.colAt(0).as<int>()
row.colAt(0).as<bool>
row.colAt(0).as<EventSomeUserDefinedType>

But in dart I can not debine traits on internal types and take them as argmuments.

So I am open to your ideas

**Comment by Ehesp** [comment]
Hmm, the problem I saw when I had a quick look was, that when you parse the binary data, you apply a Tuple of the String value and an int, but in some cases those int values are the same, e.g:

```dart
switch (columnType) {
   // ... 
    case mysqlColumnTypeLong:
    case mysqlColumnTypeInt24:
      final value = data.getInt32(startOffset, Endian.little);
      return Tuple2(value.toString(), 4);
   // ...
    case mysqlColumnTypeFloat:
      final value = data.getFloat32(startOffset, Endian.little);
      return Tuple2(value.toString(), 4);
```

I'd expect those to be different to decode, maybe a float type be decoded to a `num`, long/int etc to `int` and doubles to `double`. 

Maybe a good solution would be to decode the primitive data types, but leave the more complex ones as strings like currently, but provide the type still?

Then the tuple could become: `Tuple2<Object?, int>`, with the value decoded but the int representing the MySQL type still. That way, within an application if users wanted to deal with a geopoint themselves, they could do something simple like:

```
switch (type) {
  case mysqlColumnTypeGeometry:
    return SomeGeoPointClass(value); // let the class decode the value
  default:
    return value; // the decoded value
}
```

I could be missing something here though.

**Comment by zim32** [comment]
This is for prepared statements which uses binary protocol. You can see types here https://dev.mysql.com/doc/internals/en/binary-protocol-value.html.

As you can see 
ProtocolBinary::MYSQL_TYPE_LONG
ProtocolBinary::MYSQL_TYPE_INT24

are the same thing

**Comment by Ehesp** [comment]
Ah! Over my head half of this stuff haha.

I'm not sure what's best here. I think in general for basic primitive such as ints, doubles, bools it would be good to allow a quick conversion, but for the more complex ones just leave it as a string and let the user handle using the provides consts?

**Comment by zim32** [comment]
Ok I will think how to implement this

**Comment by zim32** [comment]
It will take some time, because a lot of tests must be written

**Comment by zim32** [comment]
Hi. You can check 0.0.11 version. There is typed... version of methods to get decoded values
